<?php

/**
 * Returns the import map for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "preload" set to true for any modules that are loaded on the initial
 *     page load to help the browser download them earlier.
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => 'app.js',
        'entrypoint' => true
    ],
    '@symfony/stimulus-bundle' => [
        'path' => '@symfony/stimulus-bundle/loader.js',
    ],
    'barecss' => [
        'url' => 'https://cdn.jsdelivr.net/npm/barecss@1.1.1/+esm',
    ],
    'barecss/css/bare.min.css' => [
        'url' => 'https://cdn.jsdelivr.net/npm/barecss@1.1.1/css/bare.min.css/+esm',
    ],
    'chart.js/auto' => [
        'url' => 'https://cdn.jsdelivr.net/npm/chart.js@4.4.0/auto/+esm',
    ],
    '@hotwired/stimulus' => [
        'url' => 'https://cdn.jsdelivr.net/npm/@hotwired/stimulus@3.2.2/+esm',
    ],
    'simple-datatables' => [
        'url' => 'https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/+esm',
    ],
    'chartjs-plugin-zoom' => [
        'url' => 'https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@2.0.1/+esm',
    ],
    'simple-datatables/dist/style.css' => [
        'url' => 'https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/dist/style.css/+esm',
    ],
];
